apiVersion: v1
kind: Service
metadata:
  name: canvas-tracker-backend
  namespace: can
spec:
  selector:
    app: canvas-tracker-backend
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canvas-tracker-backend
  namespace: can
spec:
  selector:
    matchLabels:
      app: canvas-tracker-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: canvas-tracker-backend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: canvas-tracker-backend
        image: canvas-tracker-backend-local
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: can-config
